# -*- coding: utf-8 -*-
"""Submission_Code_TML25_A1_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GymLJNPp27JCzPzsWOWmb8LJU8CoXhQ
"""

import pandas as pd
import numpy as np
import requests

df = pd.read_csv("submission.csv")

print("Submitting the following preview from submission.csv:")
print(df.head())

# Submit to server
response = requests.post(
    "http://34.122.51.94:9090/mia",
    files={"file": open("submission.csv", "rb")},
    headers={"token": "93145372"}  # Replace with actual token if needed
)

# Print server response
print("Submission response:", response.json())